SET @LOAN_ID = NULL;
CALL SP_EXECUTE_LOAN(1, @LOAN_ID);

SHOW TABLES;



SHOW PROCEDURE STATUS WHERE Db = 'db_odd_adv_4';
SHOW TABLES FROM db_odd_adv_4;

SELECT ROUTINE_SCHEMA, ROUTINE_NAME
FROM information_schema.ROUTINES
WHERE ROUTINE_NAME = 'SP_EXECUTE_LOAN';

SHOW CREATE PROCEDURE SP_CREATE_LOAN;

SELECT *
FROM information_schema.ROUTINES
WHERE ROUTINE_NAME = 'SP_CREATE_LOAN_ACCOUNT';

SELECT *
FROM information_schema.ROUTINES
WHERE ROUTINE_NAME = 'SP_CREATE_LOAN';

SHOW CREATE PROCEDURE SP_CREATE_LOAN;


