DROP PROCEDURE IF EXISTS SP_INSERT_INTR_HIST;
DELIMITER $$

CREATE PROCEDURE SP_INSERT_INTR_HIST(
   IN p_LOAN_ID BIGINT,
   IN p_BASE_RATE DECIMAL(5,3),
   IN p_ADD_RATE DECIMAL(5,3),
   IN p_PREF_RATE DECIMAL(5,3),
   IN p_FINAL_RATE DECIMAL(5,3),
   IN p_EXEC_DT DATETIME 
)
BEGIN
   
   INSERT INTO TB_LOAN_INTR_HIST (
        LOAN_ID, BASE_INTR_RT, ADD_INTR_RT, PREF_INTR_RT, APLY_INTR_RT,
        INTR_CHG_RSN_CD, APLY_DT, RGT_GUBUN, RGT_ID, RGT_DTM
    )
    VALUES (
        p_LOAN_ID, p_BASE_RATE, p_ADD_RATE, p_PREF_RATE, p_FINAL_RATE,
        '01', p_EXEC_DT, '3', 'SYS', p_EXEC_DT
    );
    END$$
DELIMITER ;

