-- 대출 상품 테이블 
CREATE TABLE TB_LOAN_PD
(
LOAN_PD_ID      BIGINT        NOT NULL COMMENT '대출상품ID',
LOAN_PD_NM      VARCHAR(100)  NOT NULL COMMENT '대출상품명',
LOAN_TP_CD      VARCHAR(10)   NOT NULL COMMENT '대출유형코드',
MAX_LIM_AMT     DECIMAL(15,0) NOT NULL COMMENT '최대한도금액',
MAX_TRM_MM      INT           NOT NULL COMMENT '최대대출기간',
INTR_TP_CD      VARCHAR(10)   NOT NULL COMMENT '금리유형코드',
RPMT_MTHD_CD    VARCHAR(10)   NOT NULL COMMENT '원금상환방식코드',
BASE_RATE_TP_CD VARCHAR(10)   NOT NULL COMMENT '기준금리유형코드',
PD_STS_CD       VARCHAR(10)   NOT NULL COMMENT '상품상태코드',

-- 컬럼 추가
RGT_GUBUN VARCHAR(2)  NOT NULL  COMMENT '등록구분 1:직원/2:고객/3:SYS',
RGT_ID    VARCHAR(10) NOT NULL  COMMENT '등록자ID',
RGT_DTM   DATETIME	 NOT NULL  COMMENT '등록일자',
MDF_ID    VARCHAR(10) NULL  	  COMMENT '수정자ID',
MDF_DTM   DATETIME	 NULL  	  COMMENT '수정일자',

CONSTRAINT PK_TB_LOAN_PD PRIMARY KEY (LOAN_PD_ID)
);

-- 대출 신청 테이블 
CREATE TABLE TB_LOAN_APLY
(
LOAN_APLY_ID   BIGINT        NOT NULL COMMENT '대출신청ID',
CUST_ID        VARCHAR(10)   NOT NULL COMMENT '고객ID',
EMP_NO         VARCHAR(10)   NULL     COMMENT '사번',
BRNCH_ID       VARCHAR(10)   NULL     COMMENT '지점ID',
LOAN_PD_ID     BIGINT        NOT NULL COMMENT '대출상품ID',
RCPT_DT        DATETIME      NOT NULL COMMENT '신청일시',
RECEIVE_DT     DATETIME      NULL     COMMENT '접수일시',
APLY_AMT       DECIMAL(15,0) NOT NULL COMMENT '신청금액',
APLY_TRM_MM    INT           NOT NULL COMMENT '신청기간(개월)',
INTR_TP_CD     VARCHAR(10)   NOT NULL COMMENT '금리유형코드',
RPMT_MTHD_CD   VARCHAR(10)   NOT NULL COMMENT '상환방식코드',
APLY_STS_CD    VARCHAR(10)   NOT NULL COMMENT '신청상태코드',
RJCT_RSN       VARCHAR(200)  NULL     COMMENT '거절사유',

-- 컬럼 추가
RGT_GUBUN VARCHAR(2)  NOT NULL  COMMENT '등록구분 1:직원/2:고객/3:SYS',
RGT_ID    VARCHAR(10) NOT NULL  COMMENT '등록자ID',
RGT_DTM   DATETIME	 NOT NULL  COMMENT '등록일자',
MDF_ID    VARCHAR(10) NULL  	  COMMENT '수정자ID',
MDF_DTM   DATETIME	 NULL  	  COMMENT '수정일자',

CONSTRAINT PK_TB_LOAN_APLY     PRIMARY KEY (LOAN_APLY_ID),
CONSTRAINT FK_LOAN_APLY_CUST   FOREIGN KEY (CUST_ID) REFERENCES TB_CUST_MST(CUST_ID),
CONSTRAINT FK_LOAN_APLY_BRANCH FOREIGN KEY (BRNCH_ID) REFERENCES TB_BRNCH_MST(BRNCH_ID),
CONSTRAINT FK_LOAN_APLY_PD     FOREIGN KEY (LOAN_PD_ID) REFERENCES TB_LOAN_PD(LOAN_PD_ID)
);

ALTER TABLE TB_LOAN_APLY
ADD CONSTRAINT FK_LOAN_APLY_EMP
FOREIGN KEY (EMP_NO)
REFERENCES TB_EMP_MST(EMP_NO);

-- 대출 테이블 
CREATE TABLE TB_LOAN
(
LOAN_ID       BIGINT         NOT NULL COMMENT '대출ID',
LOAN_APLY_ID  BIGINT         NOT NULL COMMENT '대출신청ID',
LOAN_ACCT_NO  VARCHAR(20)    NOT NULL COMMENT '대출계좌번호',
EXEC_AMT      DECIMAL(15,0)  NOT NULL COMMENT '대출실행금액',
EXEC_TRM_MM   INT            NOT NULL COMMENT '대출실행기간',
RPMT_MTHD_CD  VARCHAR(10)    NOT NULL COMMENT '상환방식코드',
INTR_TP_CD    VARCHAR(10)    NOT NULL COMMENT '금리유형코드',
APLY_INTR_RT  DECIMAL(5,3)   NOT NULL COMMENT '최신적용금리',
LOAN_STRT_DT  DATETIME       NOT NULL COMMENT '대출개시일자',
LOAN_END_DT   DATE           NOT NULL COMMENT '대출만기예정일',
DSBR_BANK_CD  VARCHAR(10)    NOT NULL COMMENT '지급은행코드',
DSBR_ACCT_NO  VARCHAR(20)    NOT NULL COMMENT '지급계좌번호',
PYMT_BANK_CD  VARCHAR(10)    NOT NULL COMMENT '상환은행코드',
PYMT_ACCT_NO  VARCHAR(20)    NOT NULL COMMENT '상환계좌번호',
LOAN_STS_CD   VARCHAR(10)    NOT NULL COMMENT '대출 상태 코드',

-- 컬럼 추가
RGT_GUBUN VARCHAR(2)  NOT NULL  COMMENT '등록구분 1:직원/2:고객/3:SYS',
RGT_ID    VARCHAR(10) NOT NULL  COMMENT '등록자ID',
RGT_DTM   DATETIME	 NOT NULL  COMMENT '등록일자',
MDF_ID    VARCHAR(10) NULL  	  COMMENT '수정자ID',
MDF_DTM   DATETIME	 NULL  	  COMMENT '수정일자',

CONSTRAINT PK_TB_LOAN       PRIMARY KEY (LOAN_ID),
CONSTRAINT FK_LOAN_APLY_ID  FOREIGN KEY (LOAN_APLY_ID) REFERENCES TB_LOAN_APLY(LOAN_APLY_ID),
CONSTRAINT FK_LOAN_ACNT_NO  FOREIGN KEY (LOAN_ACCT_NO)  REFERENCES TB_BACNT_MST(BACNT_NO),
CONSTRAINT UQ_LOAN_ACCT_NO  UNIQUE (LOAN_ACCT_NO)
);

-- 대출 상환 스케줄 테이블 
CREATE TABLE TB_LOAN_RPMT_SCHD
(
INSTL_NO        INT            NOT NULL COMMENT '회차번호',
LOAN_ID         BIGINT         NOT NULL COMMENT '대출ID',
DU_DT           DATE           NOT NULL COMMENT '상환예정일자',
PRIN_SCHD_AMT   DECIMAL(15,0)  NOT NULL COMMENT '회차예정원금',
INTR_SCHD_AMT   DECIMAL(15,0)  NOT NULL COMMENT '회차예정이자',
TOT_SCHD_AMT    DECIMAL(15,0)  NOT NULL COMMENT '회차 예정 상환금액(원리금 합계)',
REM_PRIN_AMT    DECIMAL(15,0)  NOT NULL COMMENT '상환 후 잔여 원금',
INSTL_STS_CD    VARCHAR(10)    NOT NULL COMMENT '회차 상태 코드',

-- 컬럼 추가
RGT_GUBUN VARCHAR(2)  NOT NULL  COMMENT '등록구분 1:직원/2:고객/3:SYS',
RGT_ID    VARCHAR(10) NOT NULL  COMMENT '등록자ID',
RGT_DTM   DATETIME	 NOT NULL  COMMENT '등록일자',
MDF_ID    VARCHAR(10) NULL  	  COMMENT '수정자ID',
MDF_DTM   DATETIME	 NULL  	  COMMENT '수정일자',

CONSTRAINT PK_LOAN_RPMT_SCHD PRIMARY KEY (LOAN_ID, INSTL_NO),
CONSTRAINT FK_LOAN_RPMT_SCHD FOREIGN KEY (LOAN_ID) REFERENCES TB_LOAN(LOAN_ID)
);

-- 대출 상환 테이블
CREATE TABLE TB_LOAN_RPMT
(
RPMT_ID        BIGINT         NOT NULL COMMENT '상환ID',
INSTL_NO       INT            NOT NULL COMMENT '회차번호',
LOAN_ID        BIGINT         NOT NULL COMMENT '대출ID',
PAID_AMT       DECIMAL(15,0)  NOT NULL COMMENT '납부금액',
AUTO_PYMT_YN   CHAR(1)        NOT NULL COMMENT '자동이체 여부(Y/N)', 
PAID_DT        DATETIME       NOT NULL COMMENT '상환 일시',

-- 컬럼 추가
RGT_GUBUN VARCHAR(2)  NOT NULL  COMMENT '등록구분 1:직원/2:고객/3:SYS',
RGT_ID    VARCHAR(10) NOT NULL  COMMENT '등록자ID',
RGT_DTM   DATETIME	 NOT NULL  COMMENT '등록일자',

CONSTRAINT PK_TB_LOAN_RPMT PRIMARY KEY (RPMT_ID),
CONSTRAINT FK_RPMT_TO_SCHD FOREIGN KEY (LOAN_ID, INSTL_NO) REFERENCES TB_LOAN_RPMT_SCHD (LOAN_ID, INSTL_NO)
);

-- 상환 분배 테이블
CREATE TABLE TB_LOAN_DIST (
DIST_ID         BIGINT         NOT NULL COMMENT '분배ID',
RPMT_ID         BIGINT         NOT NULL COMMENT '상환ID',
DIST_TYPE_CD    VARCHAR(2)     NOT NULL COMMENT '분배유형코드',
DIST_AMT        DECIMAL(15,0)  NOT NULL COMMENT '분배금액',
DIST_SEQ        TINYINT        NOT NULL COMMENT '분배처리순서',
    
-- 등록 정보
RGT_GUBUN       VARCHAR(2)     NOT NULL COMMENT '등록구분 (1:직원/2:고객/3:SYS)',
RGT_ID          VARCHAR(10)    NOT NULL COMMENT '등록자ID',
RGT_DTM         DATETIME       NOT NULL COMMENT '등록일자',

CONSTRAINT PK_TB_LOAN_DIST PRIMARY KEY (DIST_ID),
CONSTRAINT FK_DIST_TO_RPMT FOREIGN KEY (RPMT_ID) REFERENCES TB_LOAN_RPMT (RPMT_ID),
CONSTRAINT UQ_RPMT_TYPE UNIQUE (RPMT_ID, DIST_TYPE_CD) -- 동일 상환 건에서 동일 분배유형 중복 방지
);


-- 대출 연체 테이블
CREATE TABLE TB_LOAN_OVD (
LOAN_OVD_ID   BIGINT         NOT NULL COMMENT '연체ID',
INSTL_NO      INT            NOT NULL COMMENT '회차번호',
LOAN_ID       BIGINT         NOT NULL COMMENT '대출ID',
OVD_STRT_DT   DATE           NOT NULL COMMENT '연체 발생일자',
OVD_END_DT    DATE           NULL COMMENT '연체 해소일자',
OVD_PRIN_AMT  DECIMAL(15,0)  NOT NULL COMMENT '연체원금',
OVD_INTR_RT   DECIMAL(5,3)   NOT NULL COMMENT '연체이율',
OVD_INTR_AMT  DECIMAL(15,0)  NOT NULL COMMENT '연체이자',
OVD_DAYS      INT            NOT NULL COMMENT '연체일수',
OVD_PRIN_BAL  DECIMAL(15,0)  NOT NULL COMMENT '미해소연체원금잔액 (초기값 = OVD_PRIN_AMT)',
OVD_STS_CD    VARCHAR(10)    NOT NULL COMMENT '연체상태코드 (미납/부분해소/연체해소)',

RGT_GUBUN     VARCHAR(2)     NOT NULL COMMENT '등록구분 (1:직원/2:고객/3:SYS)',
RGT_ID        VARCHAR(10)    NOT NULL COMMENT '등록자ID',
RGT_DTM       DATETIME       NOT NULL COMMENT '등록일자',
MDF_ID        VARCHAR(10)    NULL  	  COMMENT '수정자ID',
MDF_DTM       DATETIME	     NULL  	  COMMENT '수정일자',

CONSTRAINT PK_TB_LOAN_OVD PRIMARY KEY (LOAN_OVD_ID),
CONSTRAINT FK_TB_LOAN_OVD_TO_RPMT FOREIGN KEY (LOAN_ID, INSTL_NO) REFERENCES TB_LOAN_RPMT (LOAN_ID, INSTL_NO),
CONSTRAINT UQ_OVD_RPMT UNIQUE (LOAN_ID, INSTL_NO, OVD_STRT_DT)
);


-- 대출 금리 이력 테이블
CREATE TABLE TB_LOAN_INTR_HIST (
LOAN_INTR_HIST_ID BIGINT         NOT NULL COMMENT '고객별금리이력ID',
LOAN_ID           BIGINT         NOT NULL COMMENT '대출ID',
    
BASE_INTR_RT      DECIMAL(5,3)   NOT NULL COMMENT '적용기준금리',
ADD_INTR_RT       DECIMAL(5,3)   NOT NULL COMMENT '적용가산금리',
PREF_INTR_RT      DECIMAL(5,3)   NOT NULL COMMENT '적용우대금리',
APLY_INTR_RT      DECIMAL(5,3)   NOT NULL COMMENT '최종적용금리',
    
INTR_CHG_RSN_CD   VARCHAR(10)    NULL     COMMENT '금리변경사유코드',
APLY_DT           DATETIME       NOT NULL COMMENT '적용일시',

RGT_GUBUN         VARCHAR(2)     NOT NULL COMMENT '등록구분 (1:직원/2:고객/3:SYS)',
RGT_ID            VARCHAR(10)    NOT NULL COMMENT '등록자ID',
RGT_DTM           DATETIME       NOT NULL COMMENT '등록일시',

CONSTRAINT PK_TB_LOAN_INTR_HIST PRIMARY KEY (LOAN_INTR_HIST_ID),
CONSTRAINT FK_INTR_HIST_TO_LOAN FOREIGN KEY (LOAN_ID) REFERENCES TB_LOAN (LOAN_ID)
);

-- AUTO_INCREMENT 추가 

ALTER TABLE TB_LOAN
DROP FOREIGN KEY FK_LOAN_APLY_ID;
ALTER TABLE TB_LOAN_APLY
MODIFY LOAN_APLY_ID BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE TB_LOAN
ADD CONSTRAINT FK_LOAN_APLY_ID
FOREIGN KEY (LOAN_APLY_ID)
REFERENCES TB_LOAN_APLY(LOAN_APLY_ID);

ALTER TABLE TB_LOAN_RPMT_SCHD
DROP FOREIGN KEY FK_LOAN_RPMT_SCHD;
ALTER TABLE TB_LOAN_INTR_HIST
DROP FOREIGN KEY FK_INTR_HIST_TO_LOAN;
ALTER TABLE TB_LOAN
MODIFY LOAN_ID BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE TB_LOAN_RPMT_SCHD
ADD CONSTRAINT FK_LOAN_RPMT_SCHD
FOREIGN KEY (LOAN_ID)
REFERENCES TB_LOAN(LOAN_ID);
ALTER TABLE TB_LOAN_INTR_HIST
ADD CONSTRAINT FK_INTR_HIST_TO_LOAN
FOREIGN KEY (LOAN_ID) REFERENCES TB_LOAN(LOAN_ID);

ALTER TABLE TB_LOAN_DIST
DROP FOREIGN KEY FK_DIST_TO_RPMT;
ALTER TABLE TB_LOAN_RPMT
MODIFY RPMT_ID BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE TB_LOAN_DIST
ADD CONSTRAINT FK_DIST_TO_RPMT
FOREIGN KEY (RPMT_ID) 
REFERENCES TB_LOAN_RPMT(RPMT_ID);

ALTER TABLE TB_LOAN_DIST
MODIFY DIST_ID BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE TB_LOAN_OVD
MODIFY LOAN_OVD_ID BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE TB_LOAN_INTR_HIST
MODIFY LOAN_INTR_HIST_ID BIGINT NOT NULL AUTO_INCREMENT;



































