CREATE TABLE TB_LOAN_PD
(
LOAN_PD_ID      BIGINT        NOT NULL COMMENT '대출상품ID',
LOAN_PD_NM      VARCHAR(100)  NOT NULL COMMENT '대출상품명',
LOAN_TP_CD      VARCHAR(10)   NOT NULL COMMENT '대출유형코드',
MAX_LIM_AMT     DECIMAL(15,0) NOT NULL COMMENT '최대한도금액',
MAX_TRM_MM      INT           NOT NULL COMMENT '최대대출기간',
INTR_TP_CD      VARCHAR(10)   NOT NULL COMMENT '금리유형코드',
RPMT_MTHD_CD    VARCHAR(10)   NOT NULL COMMENT '원금상환방식코드',
BASE_RATE_TP_CD VARCHAR(10)   NOT NULL COMMENT '기준금리유형코드',
PD_STS_CD       VARCHAR(10)   NOT NULL COMMENT '상품상태코드',

-- 컬럼 추가
RGT_GUBUN VARCHAR(2)  NOT NULL  COMMENT '등록구분 1:직원/2:고객/3:SYS',
RGT_ID    VARCHAR(10) NOT NULL  COMMENT '등록자ID',
RGT_DTM   DATETIME	 NOT NULL  COMMENT '등록일자',
MDF_ID    VARCHAR(10) NULL  	  COMMENT '수정자ID',
MDF_DTM   DATETIME	 NULL  	  COMMENT '수정일자',

CONSTRAINT PK_TB_LOAN_PD PRIMARY KEY (LOAN_PD_ID)
);

CREATE TABLE TB_LOAN_APLY
(
LOAN_APLY_ID   BIGINT        NOT NULL COMMENT '대출신청ID',
CUST_ID        VARCHAR(10)   NOT NULL COMMENT '고객ID',
EMP_NO         VARCHAR(10)   NULL     COMMENT '사번',
BRNCH_ID       VARCHAR(10)   NULL     COMMENT '지점ID',
LOAN_PD_ID     BIGINT        NOT NULL COMMENT '대출상품ID',
RCPT_DT        DATETIME      NOT NULL COMMENT '신청일시',
RECEIVE_DT     DATETIME      NULL     COMMENT '접수일시',
APLY_AMT       DECIMAL(15,0) NOT NULL COMMENT '신청금액',
APLY_TRM_MM    INT           NOT NULL COMMENT '신청기간(개월)',
INTR_TP_CD     VARCHAR(10)   NOT NULL COMMENT '금리유형코드',
RPMT_MTHD_CD   VARCHAR(10)   NOT NULL COMMENT '상환방식코드',
APLY_STS_CD    VARCHAR(10)   NOT NULL COMMENT '신청상태코드',
RJCT_RSN       VARCHAR(200)  NULL     COMMENT '거절사유',

-- 컬럼 추가
RGT_GUBUN VARCHAR(2)  NOT NULL  COMMENT '등록구분 1:직원/2:고객/3:SYS',
RGT_ID    VARCHAR(10) NOT NULL  COMMENT '등록자ID',
RGT_DTM   DATETIME	 NOT NULL  COMMENT '등록일자',
MDF_ID    VARCHAR(10) NULL  	  COMMENT '수정자ID',
MDF_DTM   DATETIME	 NULL  	  COMMENT '수정일자',

CONSTRAINT PK_TB_LOAN_APLY     PRIMARY KEY (LOAN_APLY_ID),
CONSTRAINT FK_LOAN_APLY_CUST   FOREIGN KEY (CUST_ID) REFERENCES TB_CUST_MST(CUST_ID),
CONSTRAINT FK_LOAN_APLY_BRANCH FOREIGN KEY (BRNCH_ID) REFERENCES TB_BRNCH_MST(BRNCH_ID),
CONSTRAINT FK_LOAN_APLY_PD     FOREIGN KEY (LOAN_PD_ID) REFERENCES TB_LOAN_PD(LOAN_PD_ID)
);

ALTER TABLE TB_LOAN_APLY
ADD CONSTRAINT FK_LOAN_APLY_EMP
FOREIGN KEY (EMP_NO)
REFERENCES TB_EMP_MST(EMP_NO);
