DROP PROCEDURE IF EXISTS SP_PROCESS_PAYMENT;
DELIMITER $$

CREATE PROCEDURE SP_PROCESS_PAYMENT(IN p_RPMT_ID BIGINT)
BEGIN 
   DECLARE v_LOAN_ID BIGINT;
   DECLARE v_INSTL_NO INT;
   DECLARE v_PAY_AMT DECIMAL(15,0);
   
   -- 연체 여부 판단용 변수
    DECLARE v_DUE_DT DATE;
    DECLARE v_TOTAL_DUE_AMT DECIMAL(15,0);
    DECLARE v_REMAINING_AMT DECIMAL(15,0);
   
   -- 1) 납부 데이터 가져오기 
   SELECT LOAN_ID, INSTL_NO, PAY_AMT
   INTO v_LOAN_ID, v_INSTL_NO, v_PAY_AMT  
   FROM TB_LOAN_RPMT
   WHERE RPMT_ID = p_RPMT_ID;
   
   -- 2) 해당 회차 스케줄 정보 조회 
   SELECT DU_DT, TOT_SCHD_AMT, REM_PRIN_AMT
    INTO v_DUE_DT, v_TOTAL_DUE_AMT, v_REMAINING_AMT
   FROM TB_LOAN_RPMT_SCHD
    WHERE LOAN_ID = v_LOAN_ID
    AND INSTL_NO = v_INSTL_NO;
    
    
END$$
DELIMITER;


