-- 신청 정보 조회 
DELIMITER $$

CREATE PROCEDURE SP_EXECUTE_LOAN(IN p_LOAN_APLY_ID BIGINT)
BEGIN 
	DECLARE v_CUST_ID VARCHAR(10); -- 고객 ID
	DECLARE v_AMT DECIMAL(15,0); -- 신청 금액
	DECLARE V_TERM INT; -- 대출 신청 기간 
	
	SELECT CUST_ID, APLY_AMT, APLY_TRM_MM
	INTO v_CUST_ID, v_AMT, v_TERM
	FROM TB_LOAN_APLY
	WHERE LOAN_APLY_ID = p_LOAN_APLY_ID; 
	
	
END$$

DELIMITER ;

CALL SP_EXECUTE_LOAN(1);
