DROP PROCEDURE IF EXISTS SP_GET_LOAN_APLY;
DELIMITER $$

CREATE PROCEDURE SP_GET_LOAN_APLY(
   IN p_LOAN_APLY_ID BIGINT,
   
   OUT o_CUST_ID      VARCHAR(10),
   OUT o_APLY_AMT     DECIMAL(15,0),
   OUT o_APLY_TRM_MM  INT,
   OUT o_LOAN_PD_ID   VARCHAR(10),
   OUT o_EXEC_DT      DATETIME,
   OUT o_INTR_TP_CD   VARCHAR(10),
   OUT o_RPMT_MTHD_CD VARCHAR(10)
)

BEGIN
  SELECT 
   CUST_ID,
   APLY_AMT,
   APLY_TRM_MM,
   LOAN_PD_ID,
   STS_CHG_DT,       -- 실행일자(= 승인일자)
   INTR_TP_CD,
   RPMT_MTHD_CD
  INTO 
   o_CUST_ID,
   o_APLY_AMT,
   o_APLY_TRM_MM,
   o_LOAN_PD_ID,
   o_EXEC_DT,
   o_INTR_TP_CD,
   o_RPMT_MTHD_CD
  FROM tb_loan_aply
  WHERE LOAN_APLY_ID = p_LOAN_APLY_ID;
  
END$$

DELIMITER ;